production:
  database: cypress_production
  hosts:
    - "localhost: 27017"

development:
  database: cypress_development
  hosts:
    - "localhost: 27017"

test:
  database: cypress_test
  hosts:
    - "localhost: 27017"